#!/bin/bash

function makedev () {

	for dev in 0 1 2 3; do
		echo "/dev/$1$dev: char $2 $dev"
		rm -f /dev/$1$dev
		mknod /dev/$1$dev c $2 $dev
		chmod 666 /dev/$1$dev
	done

	# symlink for default device
	rm -f /dev/$1
	ln -s /dev/${1}0 /dev/$1
}

makedev s626a 146

